**Instruction**:    
1. Download the ipynb, which you want to convert, on your local computer.    
2. Run the code below to upload the ipynb.  
3. The html version will be downloaded automatically on your local machine.

Enjoy it!

In [ ]:
#@title Convert ipynb to HTML in Colab
# Upload ipynb
from google.colab import files
f = files.upload()

# Convert ipynb to html
import subprocess
file0 = list(f.keys())[0]
_ = subprocess.run(["pip", "install", "nbconvert"])
_ = subprocess.run(["jupyter", "nbconvert", file0, "--to", "html"])

# download the html
files.download(file0[:-5]+"html")


In [59]:
import numpy as np
import time as t

In [7]:
set={12,13,12,'Zen','Aman','Ren','Dame',True, False}
set

{12, 13, 'Aman', 'Dame', False, 'Ren', True, 'Zen'}

In [8]:
set.add()

TypeError: set.add() takes exactly one argument (0 given)

In [13]:
dict={'name': 34.5}
dict

{'name': 34.5}

In [14]:
dict['name']=67
dict.setdefault('lastname')

In [15]:
dict

{'name': 67, 'lastname': None}

In [20]:
dict.setdefault('name')

67

In [36]:
list_1=[1,2,3,6,7]

arr1=np.array(list_1)
arr2=arr1+[1,1,1,1,1]
arr2

array([2, 3, 4, 7, 8])

In [37]:
# Size of the array
arr2.size

5

In [38]:
# Dimension of the array
arr2.ndim

1

In [39]:
# Shape function to know the number of rows and number of columns
arr2.shape

(5,)

In [40]:
# Data type of array
arr2.dtype

dtype('int64')

In [46]:
## 2D array
arr3=np.array([[1,2,3],[3,4,5]])
arr3.size
arr3.dtype

dtype('int64')

In [51]:
## 3D array
arr4=np.array([[[1,2,3],[3,4,5],[3,4,5]],[[1,2,3],[3,4,5],[3,4,5]]])
arr4.shape
# 2 is depth, 3 rows, 3 columns

(2, 3, 3)

In [53]:
m1=np.array([[1,5],[2,3]])
m2=np.array([[2,4],[6,7]])

In [54]:
m1

array([[1, 5],
       [2, 3]])

In [55]:
m2

array([[2, 4],
       [6, 7]])

### Element wise multiplication

In [56]:
# Element-wise multiplication
m1*m2

array([[ 2, 20],
       [12, 21]])

### Matrix wise multiplication

In [57]:
# Matrix multiplication
m1@m2

array([[32, 39],
       [22, 29]])

In [63]:
tic = t.time()  # capture start time
c = m1*m2
toc = t.time()  # capture end time
print(f"Element wise version duration: {1000*(toc-tic):.4f} ms ")
c

Element wise version duration: 0.1047 ms 


array([[ 2, 20],
       [12, 21]])

In [65]:
tic = t.time()  # capture start time
c = np.dot(m1,m2)
toc = t.time()  # capture end time
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")
c

Vectorized version duration: 0.1307 ms 


array([[32, 39],
       [22, 29]])

In [75]:
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
tic = t.time()  # capture start time
c = m1 @ m2
toc = t.time()  # capture end time
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")

c


Vectorized version duration: 0.0803 ms 


array([[19, 22],
       [43, 50]])

In [74]:
import numpy as np
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
tic = t.time()  # capture start time
c = np.dot(m1 , m2)
toc = t.time()  # capture end time
print(f"Vectorized version duration: {1000*(toc-tic):.4f} ms ")
c


Vectorized version duration: 0.1099 ms 


array([[19, 22],
       [43, 50]])

In [24]:
!pip install google-search-results

  Preparing metadata (setup.py) ... done
  Created wheel for google-search-results: filename=google_search_results-2.4.2-py3-none-any.whl size=32010 sha256=99359b52ce873d6b85843cd46cbc751aaefc6c77158e64276e1d3942f4d153b1
  Stored in directory: /root/.cache/pip/wheels/0c/47/f5/89b7e770ab2996baf8c910e7353d6391e373075a0ac213519e
Successfully built google-search-results


In [28]:
from serpapi.google_search import GoogleSearch

params = {
  "engine": "youtube_video",
  "v": "vFcS080VYQ0",
  "api_key": "eee604096c3c87ee509ccc3642a40bec805718f9161881c7bc2fe0e20c195ffc"
}

search = GoogleSearch(params)
results = search.get_dict()

In [29]:
results

{'search_metadata': {'id': '68c7e5bd759dbcb6d0340fc6',
  'status': 'Success',
  'json_endpoint': 'https://serpapi.com/searches/0bae0572e304ae1a/68c7e5bd759dbcb6d0340fc6.json',
  'created_at': '2025-09-15 10:09:01 UTC',
  'processed_at': '2025-09-15 10:09:01 UTC',
  'youtube_video_url': 'https://www.youtube.com/watch?v=vFcS080VYQ0',
  'raw_html_file': 'https://serpapi.com/searches/0bae0572e304ae1a/68c7e5bd759dbcb6d0340fc6.html',
  'prettify_html_file': 'https://serpapi.com/searches/0bae0572e304ae1a/68c7e5bd759dbcb6d0340fc6.prettify',
  'total_time_taken': 1.32},
 'search_parameters': {'engine': 'youtube_video', 'v': 'vFcS080VYQ0'},
 'title': 'The basics about: Coffee',
 'thumbnail': 'https://i.ytimg.com/vi/vFcS080VYQ0/maxresdefault.jpg',
 'channel': {'name': 'Old Game Box',
  'thumbnail': 'https://yt3.ggpht.com/ytc/AIdro_kMZ5WTp1HyAeBY2MwKPN5lZqyatfx9LzFKolh6v_OTdBo=s176-c-k-c0x00ffffff-no-rj',
  'link': 'https://www.youtube.com/@OldGameBox',
  'subscribers': '16.5K subscribers',
  'ext